model:
  _target_: langchain_openai.ChatOpenAI
  model: ${oc.env:HF_MODEL}
  temperature: 0.7
  top_p: 0.8
  max_tokens: 4096
  base_url: http://localhost:1333/v1
  api_key: local
  extra_body:
    chat_template_kwargs:
      enable_thinking: false
    top_k: 20
    min_p: 0